site_name: Migrate to Amazon Bedrock using LiteLLM
site_url: https://github.bedrock-litellm.com
theme:
  name: material
  features:
    - navigation.path
    - navigation.indexes
    - content.code.copy

# Website Page Tree
nav:
  - Home: 'index.md'
  # - Get Started: 'general/get-started.md'
  - Architecture: './architecture.md'
  - Deployment:
    - Prerequisites: './deploy/prerequisites.md'
    - Configure environment variables: './deploy/configure-env-variables.md'
    - Install Kubernetes tools: './deploy/tools.md'
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences